services:
  app:
    container_name: lnd-web-api
    image: lnd-web-api:v3
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  postman:
    image: postman/newman:alpine
    container_name: postman
    command: run /etc/newman/LND-Web-API.postman-collection.json
    volumes:
      - ./../postman:/etc/newman
    depends_on:
      - app
      - postgres
    network_mode: host

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    volumes:
      - ./database/src/main/resources/migrations/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
